### ISSUE TITLE
Please add RSS link

### ISSUE THREAD

**Issue by bkielbasa** [danielkvist/danielkvist.github.io#1]
It's very common to use RSS to track some blogs. RSS/Atom is perfect for it. I use hugo so I know that the link is https://dkvist.com/index.xml but I couldn't find it in the source code.

**Comment by danielkvist** [comment]
Hi!

I'm still trying to explore the theme I'm using and between that and other things I haven't had much time to personalize it as I'd like. As adding for example links to social networks and RSS.

I'll try to fix it as soon as possible.
Thank you for showing interest in my blog.
